### ISSUE TITLE
Calculo de precio final de Pedido

### ISSUE THREAD

**Issue by marcorichetta** [marcorichetta/enredarte#29]
El `precio_final` de un Pedido se guarda en un campo de la BD.
Este precio debería ser calculado en base al precio de los productos, como si fuese un atributo derivado.

### Solución
- No pasar el campo `precio_final` en el formulario de creación de pedido
- En método `save()` se hace el cálculo del precio final con los precios de todos los productos.
- Al editar un producto el cálculo no se realiza nuevamente, ya que los productos pueden haber cambiado de precio.

### Todo

- [x] Modificar el formulario de `PedidoForm` para sacar ocultar el precio
- [x] Agregar el cálculo del precio final en el modelo `Pedido`. 
- [x] Sobreescribir el campo `precio_final` del Pedido a guardar. (`form_valid()`)

### Tests
- [x] Crear pedido con productos y calcular precio
- [ ] Actualizar pedido con productos y calcular precio
